name: C Build and Run

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.txt'
    branches:
      - main
    tags-ignore:
      - '**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC(Compilation)
        run: sudo apt-get install -y build-essential

        # Compilations

      - name: Compile NumScope
        run: gcc -DCI_MODE NumScope.c -o NumScope

      - name: Compile NumScope NumCheck
        run: gcc -DCI_MODE NumScope_NumCheck.c -o NS_NumCheck

      - name: Compile NumScope Number Series Identifier
        run: gcc -DCI_MODE NumScope_Number_Series.c -o NS_Number_Series
        
      - name: Compile Armstrong Number Identifier
        run: gcc -DCI_MODE Armstrong_Number_Identifier.c -o Armstrong

      - name: Compile Disarium Number Identifer
        run: gcc -DCI_MODE Disarium_Number_Identifier.c -o Disarium

      - name: Compile Emirp Number Identifier
        run: gcc -DCI_MODE Emirp_Number_Identifier.c -o Emirp

      - name: Compile Niven Number Identifier
        run: gcc -DCI_MODE Niven_Number_Identifier.c -o Niven

      - name: Compile Palindrome Identifier
        run: gcc -DCI_MODE Palindrome_Identifier.c -o Palindrome

      - name: Compile Perfect Number Identifier
        run: gcc -DCI_MODE Perfect_Number_Identifier.c -o Perfect

      - name: Compile Spy Number Identifier
        run: gcc -DCI_MODE Spy_Number_Identifier.c -o Spy

      - name: Compile Strong Number Identifer
        run: gcc -DCI_MODE Strong_Number_Identifier.c -o Strong

      - name: Compile Twisted Primes Identifier
        run: gcc -DCI_MODE Twisted_Primes_Identifier.c -o Twisted_Primes

      # ✅ Correct Values To a Temporary File
      
      - name: Correct Input Values for NumScope Run
        run: |
          cat <<EOF > Correct_Input_Values_NumScope.txt
          A
          153
          Y
          B
          121
          Y
          C
          145
          Y
          D
          89
          Y
          E
          18
          Y
          F
          28
          Y
          G
          37
          Y
          H
          123
          Y
          I
          13
          Y
          J
          17
          N
          EOF

      #❌ Incorrect Values To a Temporary File
      
      - name: Incorrect Input Values for NumScope
        run: |
          cat <<EOF > Incorrect_Input_Values_for_NumScope.txt
          A
          152
          Y
          B
          122
          Y
          C
          146
          Y
          D
          136
          Y
          E
          19
          Y
          F
          27
          Y
          G
          13
          Y
          H
          112
          Y
          I
          12
          Y
          J
          12
          N
          EOF

      #✅ Run with Correct Values
      
      - name: Run NumScope with Correct Values
        run: |
          echo -e "✅ Correct Attempt:\n" > Results/NumScope.txt 2>&1
          ./NumScope < Correct_Input_Values_NumScope.txt >> Results/NumScope.txt 2>&1

      - name: Run Armstrong Number Identifier
        run: |
          echo -e "✅ Correct Attempt:\n" > Results/Armstrong.txt 2>&1
          echo "153" | ./Armstrong >> Results/Armstrong.txt 2>&1

      - name: Run Disarium Number Identifier
        run: |
          echo -e "✅ Correct Attempt:\n" > Results/Disarium.txt 2>&1
          echo "135" | ./Disarium >> Results/Disarium.txt 2>&1

      - name: Run Niven Number Identifier
        run: |
          echo -e "✅ Correct Attempt:\n" > Results/Niven.txt 2>&1
          echo "18" | ./Niven >> Results/Niven.txt 2>&1

      - name: Run Palindrome Identifier
        run: |
            echo -e "✅ Correct Attempt:\n" > Results/Palindrome.txt 2>&1
            echo "121" | ./Palindrome >> Results/Palindrome.txt 2>&1

      - name: Run Perfect Number Identifier
        run: |
            echo -e "✅ Correct Attempt:\n" > Results/Perfect.txt 2>&1
            echo "28" | ./Perfect >> Results/Perfect.txt 2>&1

      - name: Run Spy Number Identifier
        run: |
            echo -e "✅ Correct Attempt:\n" > Results/Spy.txt 2>&1
            echo "123" | ./Spy >> Results/Spy.txt 2>&1

      - name: Run Strong Number Identifier 
        run: |
            echo -e "✅ Correct Attempt:\n" > Results/Stong.txt 2>&1
            echo "145" | ./Strong >> Results/Strong.txt 2>&1

      - name: Run Twisted Prime Number Identifier
        run: |
            echo -e "✅ Correct Attempt:\n" > Results/Twisted_Primes.txt 2>&1
            echo "13" | ./Twisted_Primes >> Results/Twisted_Primes.txt 2>&1

      - name: Run Emirp Number Identifier
        run: |
            echo -e "✅ Correct Attempt:\n" > Results/Emirp.txt 2>&1
            echo "13" | ./Emirp >> Results/Emirp.txt 2>&1

      # ❌ Run with Incorrect Values

      - name: Run NumScope with Incorrect Values
        run: |
          echo -e "\n\n❌ Incorrect Attempt:\n" >> Results/NumScope.txt 2>&1
          ./NumScope < Incorrect_Input_Values_for_NumScope.txt >> Results/NumScope.txt 2>&1
      - name: Run Armstrong Number Identifier
        run: |
          echo -e "\n\n❌ Incorrect Attempt:\n" >> Results/Armstrong.txt 2>&1
          echo "153" | ./Armstrong >> Results/Armstrong.txt 2>&1

      - name: Run Disarium Number Identifier
        run: |
          echo -e "\n\n❌ Incorrect Attempt:\n" >> Results/Disarium.txt 2>&1
          echo "135" | ./Disarium >> Results/Disarium.txt 2>&1

      - name: Run Niven Number Identifier
        run: |
          echo -e "\n\n❌ Incorrect Attempt:\n" >> Results/Niven.txt 2>&1
          echo "18' | ./Niven >> Results/Niven.txt 2>&1

      - name: Run Palindrome Identifier
        run: |
            echo -e "\n\n❌ Incorrect Attempt:\n" >> Results/Palindrome.txt 2>&1
            echo "121" | ./Palindrome >> Results/Palindrome.txt 2>&1

      - name: Run Perfect Number Identifier
        run: |
            echo -e "\n\n❌ Incorrect Attempt:\n" >> Results/Perfect.txt 2>&1
            echo "28" | ./Perfect >> Results/Perfect.txt 2>&1

      - name: Run Spy Number Identifier
        run: |
            echo -e "\n\n❌ Incorrect Attempt:\n" >> Results/Spy.txt 2>&1
            echo "123" | ./Spy >> Results/Spy.txt 2>&1

      - name: Run Strong Number Identifier 
        run: |
            echo -e "\n\n❌ Incorrect Attempt:\n" >> Results/Stong.txt 2>&1
            echo "145" | ./Strong >> Results/Strong.txt 2>&1

      - name: Run Twisted Prime Number Identifier
        run: |
            echo -e "\n\n❌ Incorrect Attempt:\n" >> Results/Twisted_Primes.txt 2>&1
            echo "13" | ./Twisted_Primes >> Results/Twisted_Primes.txt 2>&1

      - name: Run Emirp Number Identifier
        run: |
            echo -e "\n\n❌ Incorrect Attempt:\n" >> Results/Emirp.txt 2>&1
            echo "13" | ./Emirp >> Results/Emirp.txt 2>&1

      # NumCheck

      - name: Run Numcheck
        run: |
            echo "7" | ./NS_NumCheck > Results/NS_NumCheck.txt

      # 🔢 Number Series

      # Input Values

      - name: Range Values for Number Series
        run: |
            cat <<EOF > Values_for_Number_Series.txt
            A
            1
            100
            Y
            B
            1
            100
            Y
            C
            1
            100
            Y
            D
            1
            100
            Y
            E
            1
            100
            Y
            F
            1
            100
            Y
            G
            1
            100
            Y
            H
            1
            100
            Y
            I
            1
            100
            Y
            J
            1
            100
            Y
            K
            1
            100
            Y
            L
            0
            100
            N
            EOF


      - name: Run NumScope Number Series
        run: |
          ./NS_Number_Series < Values_for_Number_Series.txt > NS_Number_Series.txt 2>&1

    # Push Run Txt Files to Repo
    
      - name: Upload NumScope output
        uses: actions/upload-artifact@v4
        with:
          name: NumScope-Run-Output
          path: Results/NumScope.txt
      - name: Push NumScope.txt to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com${{ github.repository }}
          git add Results/NumScope.txt
          git commit -m "Update NumScope output"
          git push

      - name: Upload NumScope NumCheck output
        uses: actions/upload-artifact@v4
        with:
          name: NumScope-NumCheck-Run-Output
          path: Results/NS_NumCheck.txt
      - name: Push NS_NumCheck.txt to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com${{ github.repository }}
          git add Results/NS_NumCheck.txt
          git commit -m "Update NS_NumCheck output"
          git push

      - name: Upload NumScope Number Series output
        uses: actions/upload-artifact@v4
        with:
          name: NumScope-Number-Series-Run-Output
          path: Results/NS_Number_Series.txt
      - name: Push NS_Number_Series.txt to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com${{ github.repository }}
          git add Results/NS_Number_Series.txt
          git commit -m "Update NS_Number_Series output"
          git push

      - name: Upload Armstrong Number Identifier output
        uses: actions/upload-artifact@v4
        with:
          name: Armstrong-Number-Identifier-Run-Output
          path: Results/Armstrong.txt
      - name: Push Armstrong.txt to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com${{ github.repository }}
          git add Results/Armstrong.txt
          git commit -m "Update Armstrong Number Identifier output"
          git push

      - name: Upload Disarium Number Identifier output
        uses: actions/upload-artifact@v4
        with:
          name: Disarium-Number-Identifier-Run-Output
          path: Results/Disarium.txt
      - name: Push Disarium.txt to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com${{ github.repository }}
          git add Results/Disarium.txt
          git commit -m "Update Disarium Number Identifier output"
          git push

      - name: Upload Niven Number Identifier output
        uses: actions/upload-artifact@v4
        with:
          name: Niven-Number-Identifier-Run-Output
          path: Results/Niven.txt
      - name: Push Niven.txt to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com${{ github.repository }}
          git add Results/Niven.txt
          git commit -m "Update Niven Number Identifier output"
          git push

      - name: Upload palindrome Identifier output
        uses: actions/upload-artifact@v4
        with:
          name: Palindrome-Identifier-Run-Output
          path: Results/Palindrome.txt
      - name: Push Palindrome.txt to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com${{ github.repository }}
          git add Results/Palindrome.txt
          git commit -m "Update Palindrome Identifier output"
          git push

      - name: Upload Perfect Number Identifier output
        uses: actions/upload-artifact@v4
        with:
          name: Perfect-Number-Identifier-Run-Output
          path: Results/Perfect.txt
      - name: Push Perfect.txt to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com${{ github.repository }}
          git add Results/Perfect.txt
          git commit -m "Update Perfect Number Identifier output"
          git push

      - name: Upload Spy Number Identifier output
        uses: actions/upload-artifact@v4
        with:
          name: Spy-Number-Identifier-Run-Output
          path: Results/Spy.txt
      - name: Push Spy.txt to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com${{ github.repository }}
          git add Results/Spy.txt
          git commit -m "Update Spy Number Identifier output"
          git push

      - name: Upload Strong Number Identifier output
        uses: actions/upload-artifact@v4
        with:
          name: Strong-Number-Identifier-Run-Output
          path: Results/Strong.txt
      - name: Push Strong.txt to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com${{ github.repository }}
          git add Results/Strong.txt
          git commit -m "Update Strong Number Identifier output"
          git push

      - name: Upload Twisted Prime Number Identifier output
        uses: actions/upload-artifact@v4
        with:
          name: Twisted-Prime-Number-Identifier-Run-Output
          path: Results/Twisted_Primes.txt
      - name: Push Twisted_Primes.txt to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com${{ github.repository }}
          git add Results/Twisted_Primes.txt
          git commit -m "Update Twisted Prime Number Identifier output"
          git push

      - name: Upload Emirp Number Identifier output
        uses: actions/upload-artifact@v4
        with:
          name: Emirp-Number-Identifier-Run-Output
          path: Results/Emirp.txt
      - name: Push Emirp.txt to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com${{ github.repository }}
          git add Results/Emirp.txt
          git commit -m "Update Emirp Number Identifier output"
          git push
